dist: trusty
sudo: required
language: python
python:
  - 3.6
services:
  - docker
# env:
#   global:

before_install:
  - sudo apt-get -qq update
  - pip install coveralls

install:
  - pip install requirements.txt

script:
  - make test